version: "3.8"
services:
  # food-payments-app:
  #   build: .
  #   container_name: "docker-payments-app"
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - dynamodb-local
  #     - orders-mock
  #   networks:
  #     - api-food-network
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=local

  # Rodar via terminal com  mvn spring-boot:run -Dspring-boot.run.profiles=local

  orders-mock:
    image: wiremock/wiremock:latest
    container_name: "orders-mock"
    ports:
      - 8083:8080
    volumes:
      - ./docker/wiremock/orders-api:/home/wiremock
    networks:
      - api-food-network

  users-mock:
    image: wiremock/wiremock:latest
    container_name: "users-mock"
    ports:
      - 8082:8080
    volumes:
      - ./docker/wiremock/users-api:/home/wiremock
    networks:
      - api-food-network

  mercadopago-mock:
    image: wiremock/wiremock:latest
    container_name: "mercadopago-mock"
    ports:
      - 8101:8080
    volumes:
      - ./docker/wiremock/mercadopago-api:/home/wiremock
    networks:
      - api-food-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: "dynamodb-local"
    user: root
    ports:
      - 8000:8000
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    restart: unless-stopped
    networks:
      - api-food-network
    healthcheck:
      test: ["CMD-SHELL", '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]']
      interval: 10s
      timeout: 10s
      retries: 10

  dynamodb-local-setup:
    depends_on:
      dynamodb-local:
        condition: service_healthy
    image: amazon/aws-cli
    volumes:
      - "./docker/dynamodb/schemas:/tmp/dynamo"
    environment:
      AWS_ACCESS_KEY_ID: 'dummykey'
      AWS_SECRET_ACCESS_KEY: 'dummysecret'
      AWS_REGION: 'us-east-1'
    entrypoint:
      - bash
    command:
      - '-c'
      - |
        for f in /tmp/dynamo/*.json; do
          TABLE_NAME=$$(grep -o '"TableName": *"[^"]*"' "$$f" | sed 's/"TableName": *"\(.*\)"/\1/')
          echo "Checking if table $$TABLE_NAME exists..."
          if ! aws dynamodb describe-table --endpoint-url http://dynamodb-local:8000 --table-name "$$TABLE_NAME" 2>/dev/null; then
            echo "Creating table $$TABLE_NAME..."
            aws dynamodb create-table --endpoint-url http://dynamodb-local:8000 --cli-input-json file://"$$f"
          else
            echo "Table $$TABLE_NAME already exists, skipping..."
          fi
        done
    networks:
      - api-food-network

volumes:
  mongodb_data: {}
  dynamodb_data: {}
networks:
  api-food-network:
    driver: bridge
