apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-payments
  namespace: payments
data:
  PAYMENT_INTEGRATION_HOST: "https://api.mercadopago.com/"
  SPRING_PROFILES_ACTIVE: "prod"
  AWS_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
data: {}
type: Opaque
