apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-payments
  namespace: payments
data:
  PAYMENT_INTEGRATION_HOST: "https://api.mercadopago.com/"
  SPRING_PROFILES_ACTIVE: "prd"
  AWS_REGION: "us-east-1"

