apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payments-secrets
  namespace: payments
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: payments-secrets
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: aws-acess-credentials2
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: aws-acess-credentials2
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: JWT_TOKEN_PIX_APPLICATION_PAYMENT
      remoteRef:
        key: production/payments2
        property: JWT_TOKEN_PIX_APPLICATION_PAYMENT
