apiVersion: v1
kind: Service
metadata:
  name: api-food-payments-service
spec:
  type: ClusterIP
  selector:
    app: api-food-payments
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
