spring:
  application:
    name: api-food-payments
    payment-integration:
      host1: ${PAYMENT_INTEGRATION_HOST:https://api.mercadopago.com}
      token: ${JWT_TOKEN_PIX_APPLICATION_PAYMENT}
    orders-client:
      host1: ${ORDERS_CLIENT_HOST:http://api-food-orders-service.orders}
    users-client:
      host1: ${USERS_CLIENT_HOST:http://api-food-users-service.users}

# AWS Configuration
aws:
  region: ${AWS_REGION:us-east-1}
  accesskey: ${AWS_ACCESS_KEY_ID}
  secretkey: ${AWS_SECRET_ACCESS_KEY}

user: ${ADMIN_USER:admin}
pass: ${ADMIN_PASS:admin}
