name: CI

on:
  push:
    branches: [ develop, main ]
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch: {}

jobs:
  call-reusable-build-and-test-workflow:
    uses: rachelkozlowsky/nested-reusable-java-maven-eks/.github/workflows/build.yml@main
    with:
      app_name: "pos-tech-g57-app-payments"
      dockerhub_username: "postechf57"
    secrets: inherit
    
